export type XAccount = {
  username: string
  label: string
}

export const TOPIC_X_ACCOUNTS: Record<string, XAccount[]> = {
  'ai-agi': [
    { username: 'sama', label: 'Sam Altman (OpenAI CEO)' },
    { username: 'demishassabis', label: 'Demis Hassabis (Google DeepMind CEO)' },
    { username: 'AnthropicAI', label: 'Anthropic' },
    { username: 'OpenAI', label: 'OpenAI' },
    { username: 'ylecun', label: 'Yann LeCun (Meta AI)' },
    { username: 'GaryMarcus', label: 'Gary Marcus' },
    { username: 'tegmark', label: 'Max Tegmark (MIT/FLI)' },
    { username: 'DrJimFan', label: 'Jim Fan (NVIDIA)' },
    { username: 'karpathy', label: 'Andrej Karpathy' },
    { username: 'emostaque', label: 'Emad Mostaque' },
    { username: 'GoogleDeepMind', label: 'Google DeepMind' },
    { username: 'xai', label: 'xAI' },
  ],
  cybersecurity: [
    { username: 'briankrebs', label: 'Brian Krebs' },
    { username: 'troyhunt', label: 'Troy Hunt' },
    { username: 'SwiftOnSecurity', label: 'SwiftOnSecurity' },
    { username: 'malwrhunterteam', label: 'MalwareHunterTeam' },
    { username: 'vxunderground', label: 'vx-underground' },
    { username: 'cisa_cyber', label: 'CISA' },
    { username: 'NCCGroupInfosec', label: 'NCC Group' },
  ],
  'blockchain-crypto': [
    { username: 'APompliano', label: 'Anthony Pompliano' },
    { username: 'VitalikButerin', label: 'Vitalik Buterin' },
    { username: 'CoinDesk', label: 'CoinDesk' },
    { username: 'Cointelegraph', label: 'Cointelegraph' },
    { username: 'WatcherGuru', label: 'Watcher Guru' },
    { username: 'coinbase', label: 'Coinbase' },
    { username: 'binance', label: 'Binance' },
  ],
  'ai-commercial-law': [
    { username: 'benedictevans', label: 'Benedict Evans (tech/regulation)' },
    { username: 'FTCnews', label: 'FTC' },
    { username: 'EuropeanParl_EN', label: 'European Parliament' },
    { username: 'EUAIOFFICE', label: 'EU AI Office' },
    { username: 'ai_law_policy', label: 'AI Law & Policy' },
    { username: 'techcrunch', label: 'TechCrunch' },
    { username: 'BrookingsInst', label: 'Brookings Institution' },
  ],
  'gambling-gaming-law': [
    { username: 'AGA_Advocacy', label: 'American Gaming Association' },
    { username: 'iGamingBusiness', label: 'iGaming Business' },
    { username: 'CalvinAyre', label: 'Calvin Ayre' },
    { username: 'GamblingInsider', label: 'Gambling Insider' },
    { username: 'SBC_News', label: 'SBC News' },
    { username: 'EGR_Intel', label: 'EGR Intel' },
  ],
  'data-privacy': [
    { username: 'EFF', label: 'Electronic Frontier Foundation' },
    { username: 'privacyint', label: 'Privacy International' },
    { username: 'IAPP', label: 'IAPP' },
    { username: 'Mer__edith', label: 'Meredith Whittaker (Signal)' },
    { username: 'ICOnews', label: 'UK ICO' },
    { username: 'EU_EDPS', label: 'EU Data Protection Supervisor' },
  ],
  'stock-market': [
    { username: 'markets', label: 'Bloomberg Markets' },
    { username: 'WSJ', label: 'Wall Street Journal' },
    { username: 'ReutersBiz', label: 'Reuters Business' },
    { username: 'unusual_whales', label: 'Unusual Whales (options flow)' },
    { username: 'zerohedge', label: 'ZeroHedge' },
    { username: 'CNBC', label: 'CNBC' },
    { username: 'Forbes', label: 'Forbes' },
  ],
  'vc-startups': [
    { username: 'paulg', label: 'Paul Graham' },
    { username: 'pmarca', label: 'Marc Andreessen' },
    { username: 'semil', label: 'Semil Shah' },
    { username: 'TechCrunch', label: 'TechCrunch' },
    { username: 'venturebeat', label: 'VentureBeat' },
    { username: 'Jason', label: 'Jason Calacanis' },
    { username: 'sarahtavel', label: 'Sarah Tavel (Benchmark)' },
  ],
  'global-economy': [
    { username: 'IMFNews', label: 'IMF' },
    { username: 'WorldBank', label: 'World Bank' },
    { username: 'FT', label: 'Financial Times' },
    { username: 'EconomistMag', label: 'The Economist' },
    { username: 'nytimesbusiness', label: 'NYT Business' },
    { username: 'federalreserve', label: 'Federal Reserve' },
  ],
  'biotech-health': [
    { username: 'statnews', label: 'STAT News' },
    { username: 'FiercePharma', label: 'Fierce Pharma' },
    { username: 'endpts', label: 'Endpoints News' },
    { username: 'MedPageToday', label: 'MedPage Today' },
    { username: 'BioPharmaDive', label: 'BioPharma Dive' },
  ],
  'climate-energy': [
    { username: 'CarbonBrief', label: 'Carbon Brief' },
    { username: 'ClimateReporter', label: 'Climate Reporter' },
    { username: 'iea', label: 'IEA' },
    { username: 'GretaThunberg', label: 'Greta Thunberg' },
    { username: 'ClimateNexus', label: 'Climate Nexus' },
    { username: 'caneurope', label: 'CAN Europe' },
  ],
  'space-defense': [
    { username: 'SpaceX', label: 'SpaceX' },
    { username: 'NASA', label: 'NASA' },
    { username: 'elonmusk', label: 'Elon Musk' },
    { username: 'esa', label: 'ESA' },
    { username: 'DefenseOne', label: 'Defense One' },
    { username: 'AviationWeek', label: 'Aviation Week' },
  ],
}

export const NITTER_INSTANCES = [
  'nitter.privacydev.net',
  'nitter.poast.org',
  'nitter.cz',
  'nitter.1d4.us',
]
