-- Add image_url to articles
ALTER TABLE articles ADD COLUMN IF NOT EXISTS image_url TEXT;

-- New topics (38 additions to reach 50 total)
INSERT INTO topics (id, name, slug, description, icon) VALUES
  ('us-politics',       'US Politics',                    'us-politics',        'American political news, Congress, White House, and policy',                    '🇺🇸'),
  ('geopolitics',       'Geopolitics',                    'geopolitics',        'International relations, foreign policy, and global power dynamics',            '🌐'),
  ('entertainment',     'Entertainment',                  'entertainment',      'Celebrity news, awards, music, and pop culture',                               '🎬'),
  ('classical-opera',   'Classical Music & Opera',        'classical-opera',    'Orchestras, opera houses, conductors, composers, and performances',            '🎼'),
  ('judaism',           'Judaism & Jewish World',         'judaism',            'Jewish culture, Israel, diaspora communities, and religious life',              '✡️'),
  ('sports',            'Sports',                         'sports',             'Football, basketball, tennis, golf, and all major sporting events',             '🏆'),
  ('real-estate',       'Real Estate',                    'real-estate',        'Property markets, housing, commercial real estate, and REITs',                 '🏠'),
  ('food-drink',        'Food & Drink',                   'food-drink',         'Restaurants, chefs, food trends, wine, and culinary culture',                  '🍽️'),
  ('fashion-luxury',    'Fashion & Luxury',               'fashion-luxury',     'High fashion, luxury brands, retail trends, and style',                        '👗'),
  ('science',           'Science & Research',             'science',            'Discoveries in physics, chemistry, biology, and scientific research',           '🔬'),
  ('gaming-esports',    'Gaming & Esports',               'gaming-esports',     'Video games, esports tournaments, gaming industry, and game releases',         '🎮'),
  ('consumer-tech',     'Consumer Tech',                  'consumer-tech',      'Smartphones, gadgets, apps, and everyday technology products',                 '📱'),
  ('film-tv',           'Film & Television',              'film-tv',            'Movies, TV shows, streaming, directors, and screen industry news',             '🎥'),
  ('literature',        'Literature & Books',             'literature',         'New books, authors, publishing, literary criticism, and reading culture',       '📚'),
  ('art-design',        'Art & Design',                   'art-design',         'Visual art, galleries, museums, graphic design, and creative culture',         '🎨'),
  ('media-journalism',  'Media & Journalism',             'media-journalism',   'Press freedom, newsroom business, media trends, and journalism',               '📰'),
  ('mental-health',     'Mental Health',                  'mental-health',      'Psychology, therapy, wellbeing research, and mental health policy',            '🧠'),
  ('travel',            'Travel',                         'travel',             'Destinations, aviation, hospitality, travel trends, and tourism',               '✈️'),
  ('automotive-ev',     'Automotive & EVs',               'automotive-ev',      'Car industry, electric vehicles, autonomous driving, and mobility',            '🚗'),
  ('robotics',          'Robotics & Automation',          'robotics',           'Industrial robots, humanoids, automation technology, and manufacturing',       '🦾'),
  ('nuclear',           'Nuclear Energy & Policy',        'nuclear',            'Nuclear power plants, fusion research, non-proliferation, and energy policy',  '⚛️'),
  ('trade-tariffs',     'Trade & Tariffs',                'trade-tariffs',      'International trade, tariffs, sanctions, WTO, and supply chains',              '📦'),
  ('elections',         'Elections & Democracy',          'elections',          'Voting, electoral systems, campaign finance, and democratic institutions',      '🗳️'),
  ('military',          'Military & Defense',             'military',           'Armed forces, weapons systems, veterans, and defense procurement',             '🎖️'),
  ('emerging-markets',  'Emerging Markets',               'emerging-markets',   'Economies of Asia, Africa, Latin America, and frontier markets',               '📊'),
  ('aviation',          'Aviation & Transport',           'aviation',           'Airlines, airports, rail, shipping, and the future of transport',              '🛫'),
  ('agriculture',       'Agriculture & Food Security',    'agriculture',        'Farming, crop science, food supply chains, and rural economies',               '🌾'),
  ('human-rights',      'Human Rights',                   'human-rights',       'Civil liberties, humanitarian issues, NGOs, and international justice',        '✊'),
  ('religion',          'Religion & Spirituality',        'religion',           'Faith communities, theology, interfaith dialogue, and religious affairs',      '🕊️'),
  ('environment',       'Environment & Biodiversity',     'environment',        'Wildlife, oceans, deforestation, conservation, and ecological science',        '🌿'),
  ('health-wellness',   'Health & Wellness',              'health-wellness',    'Nutrition, fitness, public health, medicine, and healthy living',              '💊'),
  ('philosophy',        'Philosophy & Ethics',            'philosophy',         'Moral philosophy, political theory, logic, and applied ethics',                '🤔'),
  ('education',         'Education',                      'education',          'Schools, universities, EdTech, pedagogy, and education policy',                '🎓'),
  ('immigration',       'Immigration & Migration',        'immigration',        'Immigration policy, asylum, border issues, and diaspora communities',          '🛂'),
  ('labor',             'Labor & Employment',             'labor',              'Workers rights, unions, wages, remote work, and employment trends',            '👷'),
  ('architecture',      'Architecture & Urbanism',        'architecture',       'Buildings, urban planning, infrastructure, and architectural design',          '🏛️'),
  ('social-media-tech', 'Social Media & Big Tech',        'social-media-tech',  'Platforms, algorithms, content moderation, and tech giants',                  '📲'),
  ('pharma',            'Pharmaceuticals',                'pharma',             'Drug development, FDA approvals, clinical trials, and pharma industry',        '💉')
ON CONFLICT (id) DO NOTHING;
